# Generated by Django 5.0.1 on 2024-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbApp', '0005_base5_car_dupemployee_base6_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
