# Generated by Django 5.0.1 on 2024-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=30)),
                ('AuthorName', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('FeedBack', models.CharField(max_length=40)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
